import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "picoin.sqlite3"

PROJECT_NAME = "picoin-proof-of-pi"
PROTOCOL_VERSION = "0.14"
NETWORK_ID = os.getenv("PICOIN_NETWORK", "local").strip().lower() or "local"
VALIDATION_MODE = "external_commit_reveal"
REQUIRED_VALIDATOR_APPROVALS = 2
RANGE_ASSIGNMENT_MODE = "pseudo_random"
MAX_PI_POSITION = 10_000
RANGE_ASSIGNMENT_MAX_ATTEMPTS = 512
TASK_SEGMENT_SIZE = 64
TASK_START_OFFSET = 1
TASK_EXPIRATION_SECONDS = 10 * 60
MAX_ACTIVE_TASKS_PER_MINER = 1
SAMPLE_COUNT = 8
DEFAULT_REWARD = 3.1416
VALIDATOR_REWARD_PERCENT_OF_BLOCK = 0.10
PI_ALGORITHM = "bbp_hex_v1"
GENESIS_ACCOUNT_ID = "genesis"
GENESIS_SUPPLY = 3_141_600.0
FAUCET_DEFAULT_AMOUNT = 31.416
FAUCET_MAX_AMOUNT = 314.16
FAUCET_ALLOWED_NETWORKS = {"local"}
FAUCET_RATE_LIMIT_WINDOW_SECONDS = 60 * 60
FAUCET_RATE_LIMIT_MAX_REQUESTS = 3
MIN_VALIDATOR_STAKE = 31.416
VALIDATOR_SLASH_INVALID_SIGNATURE = 3.1416
VALIDATOR_MIN_TRUST_SCORE = 0.25
VALIDATOR_SELECTION_MODE = "weighted_reputation_stake_rotation"
VALIDATOR_SELECTION_POOL_MULTIPLIER = 2
VALIDATOR_SELECTION_TRUST_WEIGHT = 0.55
VALIDATOR_SELECTION_STAKE_WEIGHT = 0.25
VALIDATOR_SELECTION_AVAILABILITY_WEIGHT = 0.10
VALIDATOR_SELECTION_ROTATION_WEIGHT = 0.10
VALIDATOR_AVAILABILITY_WINDOW_SECONDS = 60 * 60
VALIDATOR_ROTATION_WINDOW_SECONDS = 60 * 60
BASE_DIFFICULTY_SEGMENT_SIZE = 64
BASE_DIFFICULTY_SAMPLE_COUNT = 8
BASE_DIFFICULTY_MAX_PI_POSITION = 10_000
RETARGET_EPOCH_BLOCKS = 5
RETARGET_TARGET_BLOCK_MS = 60_000
RETARGET_TOLERANCE = 0.20
RETARGET_MAX_ADJUSTMENT_FACTOR = 1.25
RETARGET_MIN_SEGMENT_SIZE = 16
RETARGET_MAX_SEGMENT_SIZE = 256
RETARGET_MIN_SAMPLE_COUNT = 4
RETARGET_MAX_SAMPLE_COUNT = 16
RETARGET_MIN_PI_POSITION = 10_000
RETARGET_MAX_PI_POSITION = 100_000

PENALTY_INVALID_RESULT = 1
PENALTY_DUPLICATE = 3
PENALTY_INVALID_SIGNATURE = 5
COOLDOWN_AFTER_REJECTIONS = 3
COOLDOWN_SECONDS = 5 * 60
TASK_RATE_LIMIT_WINDOW_SECONDS = 60
TASK_RATE_LIMIT_MAX_ASSIGNMENTS = 12
VALIDATOR_PENALTY_INVALID_SIGNATURE = 2
VALIDATOR_COOLDOWN_AFTER_INVALID_RESULTS = 3
VALIDATOR_BAN_AFTER_INVALID_RESULTS = 9
VALIDATOR_COOLDOWN_SECONDS = 10 * 60
