import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "picoin.sqlite3"

PROJECT_NAME = "picoin-proof-of-pi"
PROTOCOL_VERSION = "0.17"
NETWORK_ID = os.getenv("PICOIN_NETWORK", "local").strip().lower() or "local"
CHAIN_ID = os.getenv("PICOIN_CHAIN_ID", f"picoin-{NETWORK_ID}-testnet").strip() or f"picoin-{NETWORK_ID}-testnet"
GENESIS_HASH = os.getenv("PICOIN_GENESIS_HASH", "0" * 64).strip() or ("0" * 64)
NODE_ID = os.getenv("PICOIN_NODE_ID", "local-node").strip() or "local-node"
NODE_TYPE = os.getenv("PICOIN_NODE_TYPE", "full").strip().lower() or "full"
NODE_PUBLIC_ADDRESS = os.getenv("PICOIN_NODE_ADDRESS", "http://127.0.0.1:8000").strip()
BOOTSTRAP_PEERS = tuple(
    peer.strip().rstrip("/")
    for peer in os.getenv("PICOIN_BOOTSTRAP_PEERS", "").split(",")
    if peer.strip()
)
CORS_ORIGINS = tuple(
    origin.strip().rstrip("/")
    for origin in os.getenv("PICOIN_CORS_ORIGINS", "").split(",")
    if origin.strip()
)
PEER_TIMEOUT_SECONDS = int(os.getenv("PICOIN_PEER_TIMEOUT_SECONDS", "90"))
MEMPOOL_TX_TTL_SECONDS = int(os.getenv("PICOIN_MEMPOOL_TX_TTL_SECONDS", "3600"))
MEMPOOL_MAX_FEE = float(os.getenv("PICOIN_MEMPOOL_MAX_FEE", "31.416"))
MAX_TRANSACTIONS_PER_BLOCK = int(os.getenv("PICOIN_MAX_TRANSACTIONS_PER_BLOCK", "100"))
GOSSIP_ENABLED = os.getenv("PICOIN_GOSSIP_ENABLED", "1").strip().lower() not in {"0", "false", "no"}
GOSSIP_TIMEOUT_SECONDS = float(os.getenv("PICOIN_GOSSIP_TIMEOUT_SECONDS", "2.0"))
GOSSIP_MAX_PEERS = int(os.getenv("PICOIN_GOSSIP_MAX_PEERS", "16"))
CHECKPOINT_INTERVAL_BLOCKS = int(os.getenv("PICOIN_CHECKPOINT_INTERVAL_BLOCKS", "10"))
VALIDATION_MODE = "external_commit_reveal"
REQUIRED_VALIDATOR_APPROVALS = 3
RANGE_ASSIGNMENT_MODE = "pseudo_random"
MAX_PI_POSITION = 10_000
RANGE_ASSIGNMENT_MAX_ATTEMPTS = 512
TASK_SEGMENT_SIZE = 64
TASK_START_OFFSET = 1
TASK_EXPIRATION_SECONDS = 10 * 60
MAX_ACTIVE_TASKS_PER_MINER = 1
SAMPLE_COUNT = 32
DEFAULT_REWARD = 3.1416
VALIDATOR_REWARD_PERCENT_OF_BLOCK = 0.10
PROOF_OF_PI_REWARD_PERCENT = 0.67
SCIENCE_COMPUTE_REWARD_PERCENT_OF_BLOCK = 0.20
VALIDATOR_AUDITOR_REWARD_PERCENT = 0.10
SCIENCE_RESERVE_ACCOUNT_ID = "science_compute_reserve"
SCIENCE_MAX_REWARD_PER_JOB = float(os.getenv("PICOIN_SCIENCE_MAX_REWARD_PER_JOB", "314.16"))
SCIENCE_MAX_PAYOUT_PER_EPOCH = float(os.getenv("PICOIN_SCIENCE_MAX_PAYOUT_PER_EPOCH", "3141.6"))
SCIENCE_MAX_PENDING_PER_REQUESTER = float(os.getenv("PICOIN_SCIENCE_MAX_PENDING_PER_REQUESTER", "314.16"))
SCIENTIFIC_DEVELOPMENT_REWARD_PERCENT_OF_BLOCK = 0.03
SCIENTIFIC_DEVELOPMENT_TREASURY_ACCOUNT_ID = "scientific_development_treasury"
SCIENTIFIC_DEVELOPMENT_TREASURY_WALLET = os.getenv(
    "PICOIN_TREASURY_WALLET",
    "picoin_scientific_development_wallet",
).strip()
SCIENTIFIC_DEVELOPMENT_GOVERNANCE_WALLET = os.getenv(
    "PICOIN_GOVERNANCE_WALLET",
    "picoin_governance_multisig",
).strip()
SCIENTIFIC_DEVELOPMENT_UNLOCK_INTERVAL_DAYS = 90
SCIENCE_BASE_MONTHLY_QUOTA_UNITS = 100
SCIENCE_ALLOW_SELF_WORK = False
SCIENCE_RESERVE_LOCKED_STATUS = "RESERVE_LOCKED"
SCIENCE_RESERVE_PENDING_STATUS = "L2_PENDING"
SCIENCE_RESERVE_ACTIVE_STATUS = "L2_ACTIVE"
SCIENCE_RESERVE_PAUSED_STATUS = "EMERGENCY_PAUSED"
SCIENCE_RESERVE_GOVERNANCE_TIMELOCK_SECONDS = 24 * 60 * 60
SCIENCE_RESERVE_GOVERNANCE_MULTISIG_THRESHOLD = 2
SCIENCE_RESERVE_AUTHORIZED_SIGNERS = tuple(
    signer.strip()
    for signer in os.getenv("PICOIN_SCIENCE_RESERVE_AUTHORIZED_SIGNERS", "signer-1,signer-2").split(",")
    if signer.strip()
)
RETROACTIVE_AUDIT_INTERVAL_BLOCKS = 314
RETROACTIVE_AUDIT_SAMPLE_MULTIPLIER = 2
RETROACTIVE_AUDIT_REWARD_PERCENT_OF_BLOCK = 0.20
RETROACTIVE_AUDIT_REWARD_ACCOUNT_ID = "audit_treasury"
FRAUD_MINER_PENALTY_POINTS = 20
FRAUD_VALIDATOR_INVALID_RESULTS = 3
FRAUD_COOLDOWN_SECONDS = 60 * 60
PI_ALGORITHM = "bbp_hex_v1"
GENESIS_ACCOUNT_ID = "genesis"
GENESIS_SUPPLY = 3.1416
FAUCET_DEFAULT_AMOUNT = 3.1416
FAUCET_MAX_AMOUNT = 3.1416
FAUCET_ALLOWED_NETWORKS = {"local"}
FAUCET_RATE_LIMIT_WINDOW_SECONDS = 60 * 60
FAUCET_RATE_LIMIT_MAX_REQUESTS = 3
MIN_VALIDATOR_STAKE = 31.416
VALIDATOR_SLASH_INVALID_SIGNATURE = 3.1416
VALIDATOR_MIN_TRUST_SCORE = 0.25
VALIDATOR_SELECTION_MODE = "weighted_reputation_stake_rotation"
VALIDATOR_SELECTION_POOL_MULTIPLIER = 2
VALIDATOR_SELECTION_TRUST_WEIGHT = 0.55
VALIDATOR_SELECTION_STAKE_WEIGHT = 0.25
VALIDATOR_SELECTION_AVAILABILITY_WEIGHT = 0.10
VALIDATOR_SELECTION_ROTATION_WEIGHT = 0.10
VALIDATOR_AVAILABILITY_WINDOW_SECONDS = 60 * 60
VALIDATOR_ROTATION_WINDOW_SECONDS = 60 * 60
BASE_DIFFICULTY_SEGMENT_SIZE = 64
BASE_DIFFICULTY_SAMPLE_COUNT = 8
BASE_DIFFICULTY_MAX_PI_POSITION = 10_000
RETARGET_EPOCH_BLOCKS = 5
RETARGET_TARGET_BLOCK_MS = 60_000
RETARGET_TOLERANCE = 0.20
RETARGET_MAX_ADJUSTMENT_FACTOR = 1.25
RETARGET_MIN_SEGMENT_SIZE = 16
RETARGET_MAX_SEGMENT_SIZE = 256
RETARGET_MIN_SAMPLE_COUNT = 8
RETARGET_MAX_SAMPLE_COUNT = 64
RETARGET_MIN_PI_POSITION = 10_000
RETARGET_MAX_PI_POSITION = 100_000

PENALTY_INVALID_RESULT = 1
PENALTY_DUPLICATE = 3
PENALTY_INVALID_SIGNATURE = 5
COOLDOWN_AFTER_REJECTIONS = 3
COOLDOWN_SECONDS = 5 * 60
TASK_RATE_LIMIT_WINDOW_SECONDS = 60
TASK_RATE_LIMIT_MAX_ASSIGNMENTS = 12
VALIDATOR_PENALTY_INVALID_SIGNATURE = 2
VALIDATOR_COOLDOWN_AFTER_INVALID_RESULTS = 3
VALIDATOR_BAN_AFTER_INVALID_RESULTS = 9
VALIDATOR_COOLDOWN_SECONDS = 10 * 60
