from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "picoin.sqlite3"

PROJECT_NAME = "picoin-proof-of-pi"
PROTOCOL_VERSION = "0.8"
VALIDATION_MODE = "external_commit_reveal"
REQUIRED_VALIDATOR_APPROVALS = 1
RANGE_ASSIGNMENT_MODE = "pseudo_random"
MAX_PI_POSITION = 10_000
RANGE_ASSIGNMENT_MAX_ATTEMPTS = 512
TASK_SEGMENT_SIZE = 64
TASK_START_OFFSET = 1
TASK_EXPIRATION_SECONDS = 10 * 60
MAX_ACTIVE_TASKS_PER_MINER = 1
SAMPLE_COUNT = 8
DEFAULT_REWARD = 3.14159
PI_ALGORITHM = "bbp_hex_v1"
BASE_DIFFICULTY_SEGMENT_SIZE = 64
BASE_DIFFICULTY_SAMPLE_COUNT = 8
BASE_DIFFICULTY_MAX_PI_POSITION = 10_000

PENALTY_INVALID_RESULT = 1
PENALTY_DUPLICATE = 3
PENALTY_INVALID_SIGNATURE = 5
COOLDOWN_AFTER_REJECTIONS = 3
COOLDOWN_SECONDS = 5 * 60
