from __future__ import annotations

from pathlib import Path

from .scanner import scan_repo
from .utils import forge_dir, load_project_map, repo_root, write_text_safe


def generate_install_plan(repo_path: str | Path) -> Path:
    root = repo_root(repo_path)
    project_map = load_project_map(root) or scan_repo(root)
    managers = set(project_map.get("package_managers") or [])
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by Picoin Forge AI.",
        "# Review this script before running it. It never calls sudo by default.",
        f"cd {shell_quote(str(root))}",
        "",
    ]
    if "python" in managers:
        lines.extend(
            [
                "python3 -m venv .venv",
                "source .venv/bin/activate",
                "python -m pip install --upgrade pip",
                "if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
                "if [ -f pyproject.toml ]; then pip install -e .; fi",
                "",
            ]
        )
    if "node" in managers:
        lines.extend(["if [ -f package.json ]; then npm install; fi", ""])
    if "go" in managers:
        lines.extend(["if [ -f go.mod ]; then go mod download; fi", ""])
    if "rust" in managers:
        lines.extend(["if [ -f Cargo.toml ]; then cargo build; fi", ""])
    if not managers:
        lines.append("echo 'No known package manager detected. Review project-map.json.'")
    path = forge_dir(root) / "scripts" / "install.sh"
    write_text_safe(path, "\n".join(lines) + "\n")
    return path


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"
