from __future__ import annotations

DEFAULT_EPOCH_REWARD_PI = 100.0
DEFAULT_AI_ACCESS_MIN_STAKE_PI = 1.0
DEFAULT_AI_REQUEST_LEASE_SECONDS = 120
DEFAULT_AI_REQUEST_MAX_ASSIGNMENTS = 3
DEFAULT_CHALLENGE_TTL_SECONDS = 300
DEFAULT_COORDINATOR_STATE_DIR = ".picoin-forge-l2"
DEFAULT_WORKER_STATE_DIR = ".picoin-forge-worker"
DEFAULT_HEARTBEAT_GRACE_SECONDS = 180
MISSED_HEARTBEAT_PENALTY = 2.0
EXPIRED_CHALLENGE_PENALTY = 5.0

CPU_WEIGHT = 1.0
GPU_WEIGHT = 2.5
AI_MODEL_WEIGHT = 3.0
RAM_WEIGHT = 0.35
IO_WEIGHT = 0.25
UPTIME_WEIGHT = 0.50
RELIABILITY_WEIGHT = 0.75

MIN_RELIABILITY_SCORE = 0.0
MAX_RELIABILITY_SCORE = 100.0
MAX_UPTIME_SCORE = 100.0
